In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#create random initial spins in an NxN array?
#Need to take into account the position of the spins

#Pick one random spin and flip it
#Calculate energy difference between the old and the new state
#If E_new > E_old: keep new state
#If E_new < E_old: calculate q = p(x')/p(x).
#Draw random number: if random number lower than q: accept new state

In [206]:
def spin(spin_value):
    alignment = bool(spin_value)
    if alignment == True:
        s = 1
    if alignment == False:
        s = -1
    return s

def choose_flip(lattice, n_spins):
    dim = len(lattice[0,:])
    random_x = np.random.randint(0,n_spins)
    random_y = np.random.randint(0,n_spins)
    flip_lattice = -lattice[random_x, random_y]
    lattice[random_x, random_y] = flip_lattice
    return lattice, random_x, random_y

def energy_difference(old_lattice, new_lattice):
    delta_energy = total_hamiltonian(new_lattice) - total_hamiltonian(old_lattice)
    return delta_energy

# def total_hamiltonian(lattice, coupling_constant=1):
#     dim = len(lattice[0,:])
#     ham = 0
#     #Now the same point is multiplied
#     for i in range(dim):
#         for j in range(dim):
#             h = 0
#             if j != i and np.abs(j-i)==1:
#                 h = lattice[i,j]*lattice[i,j]
#             ham += h
#     total_ham = -coupling_constant*ham
#     return total_ham

def total_hamiltonian(lattice, coupling_constant=1):
    n_spins = 10
    L = n_spins
    dim = len(lattice[0,:])
    ham = 0
    for i in range(dim):
        for j in range(dim):
            h = 0
            h = lattice[i,j]*lattice[(i-1)%L,j-1] + lattice[i,j]*lattice[(i-1)%L,(j+1)%L] + lattice[i,j]*lattice[(i+1)%L,(j+1)%L] + lattice[i,j]*lattice[(i+1)%L,(j-1)%L]
            ham += h
    total_ham = -coupling_constant*ham
    print(total_ham)
    return total_ham

def accept_new_state(en_diff, beta):
    if en_diff > 0:
        accept_state = True
    if en_diff < 0:
        accept_prob = np.exp(beta*en_diff)
        random_number = np.random.uniform(0,1)
        if random_number < accept_prob:
            accept_state = True
        else:
            accept_state = False
    return accept_state

def total_energy(accept_state, system_energy, en_diff):
    if accept_new_state = True:
        new_energy = system_energy+en_diff
        system_energy.append(new_energy)
    return system_energy

def total_magnetisation(accept_state, new_lattice):
    if accept_new_state = True:
        system_magnetisation.append(np.sum(new_lattice))
    return system_magnetisation
    
def initial_spins(N):
    lattice = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            random_spin = np.random.randint(0,2)
            spin_value = spin(random_spin)
            lattice[i,j] = spin_value
    
    return lattice

In [249]:
#Define constants
n_spins = 10
coupling_constant = 1
temperature = 1
beta = 1/temperature

#Define initial spins in lattice, magnetisation, and energy
def initial_system(n_spins)
    init_lattice = initial_spins(n_spins)
    #print(init_lattice)
    system_energy = [total_hamiltonian(init_lattice)]
    system_magnetisation = [np.sum(init_lattice)]
    return init_lattice, system_energy, system_magnetisation

[[ 1. -1. -1. -1. -1. -1.  1. -1.  1. -1.]
 [-1. -1.  1. -1.  1. -1.  1. -1.  1. -1.]
 [-1. -1.  1. -1.  1.  1. -1.  1. -1. -1.]
 [-1.  1. -1.  1.  1.  1. -1.  1.  1. -1.]
 [ 1. -1.  1. -1.  1. -1. -1. -1. -1. -1.]
 [ 1. -1. -1.  1.  1.  1.  1.  1. -1. -1.]
 [-1. -1. -1. -1.  1. -1. -1.  1. -1. -1.]
 [ 1.  1.  1. -1.  1.  1. -1. -1.  1. -1.]
 [ 1. -1.  1.  1.  1. -1. -1.  1.  1. -1.]
 [ 1.  1. -1.  1.  1. -1.  1. -1.  1. -1.]]


In [248]:
#Flip a spin
new_state = choose_flip(init_lattice, n_spins)
new_lattice = new_state[0]
print(new_state[1])
print(new_state[2])

#calculate energy difference
en_diff = energy_difference(init_lattice, new_lattice)
print(en_diff)

5
9
-48.0
-32.0
-16.0


In [ ]:
#See if en diff is greater/smaller
#accept_new_state function
#total_energy function
#total_magnetisation function

In [ ]:
#Do it again:
#choose_flip etc

In [ ]:
def ising_simulation(init_lattice, n_spins)
    for i in range(2):
        new_state = choose_flip(init_lattice, n_spins)
        new_lattice = new_state[0]
        en_diff = energy_difference(init_lattice, new_lattice)