In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#create random initial spins in an NxN array?
#Need to take into account the position of the spins

#Pick one random spin and flip it
#Calculate energy difference between the old and the new state
#If E_new > E_old: keep new state
#If E_new < E_old: calculate q = p(x')/p(x).
#Draw random number: if random number lower than q: accept new state

In [3]:
def spin(spin_value):
    alignment = bool(spin_value)
    if alignment == True:
        s = 1.0
    if alignment == False:
        s = -1.0
    return s

def choose_flip(lattice):
    dim = len(lattice[0,:])
    random_x = np.random.randint(0,dim)
    random_y = np.random.randint(0,dim)
    flip = lattice[random_x, random_y]
    flip *= -1
#     flip_lattice = -lattice[random_x, random_y]
#     print(lattice[random_x, random_y])
#     print(flip_lattice)
    lattice[random_x, random_y] = flip

    return lattice, random_x, random_y

def energy_difference(old_lattice, new_lattice):
    delta_energy = total_hamiltonian(new_lattice) - total_hamiltonian(old_lattice)
    return delta_energy

# def total_hamiltonian(lattice, coupling_constant=1):
#     dim = len(lattice[0,:])
#     ham = 0
#     #Now the same point is multiplied
#     for i in range(dim):
#         for j in range(dim):
#             h = 0
#             if j != i and np.abs(j-i)==1:
#                 h = lattice[i,j]*lattice[i,j]
#             ham += h
#     total_ham = -coupling_constant*ham
#     return total_ham

def total_hamiltonian(lattice, coupling_constant=1):
    n_spins = 10
    L = n_spins
    dim = len(lattice[0,:])
    ham = 0
    for i in range(dim):
        for j in range(dim):
            h = 0
            h = lattice[i,j]*lattice[(i-1)%L,j-1] + lattice[i,j]*lattice[(i-1)%L,(j+1)%L] + lattice[i,j]*lattice[(i+1)%L,(j+1)%L] + lattice[i,j]*lattice[(i+1)%L,(j-1)%L]
            ham += h
    total_ham = -coupling_constant*ham
#     print(total_ham)
    return total_ham

def accept_new_state(en_diff, beta):
    if en_diff > 0:
        accept_state = True
    if en_diff < 0:
        accept_prob = np.exp(beta*en_diff)
        random_number = np.random.uniform(0,1)
        if random_number < accept_prob:
            accept_state = True
        else:
            accept_state = False
    return accept_state

def total_energy(accept_state, system_energy, en_diff):
    if accept_new_state == True:
        new_energy = system_energy+en_diff
        system_energy.append(new_energy)
    return system_energy

def total_magnetisation(accept_state, new_lattice):
    if accept_new_state == True:
        system_magnetisation.append(np.sum(new_lattice))
    return system_magnetisation
    
def initial_spins(N):
    lattice = np.zeros((N, N))
    for i in range(N):
        for j in range(N):
            random_spin = np.random.randint(0,2)
            spin_value = spin(random_spin)
            lattice[i,j] = spin_value
    
    return lattice


        
        
def initial_system(n_spins):
    init_lattice = initial_spins(n_spins)
    print(init_lattice)
    system_energy = [total_hamiltonian(init_lattice)]
    system_magnetisation = [np.sum(init_lattice)]
    return init_lattice, system_energy, system_magnetisation

def ising_simulation(in_lattice):
    lattice = in_lattice
    for i in range(10):
        lattice_copy = np.copy(lattice)  # make a copy of init_lattice
        new_state = choose_flip(lattice_copy)
        new_lattice = new_state[0]
        print(new_lattice - lattice)
        en_diff = energy_difference(lattice, new_lattice)
        print('Delta E: ', en_diff)
        lattice = new_lattice

In [4]:
#Define constants
n_spins = 10
coupling_constant = 1
temperature = 1
beta = 1/temperature

#Define initial spins in lattice, magnetisation, and energy


In [5]:
init_lattice, system_energy, system_magnetisation = initial_system(n_spins)


[[ 1. -1. -1. -1.  1. -1.  1.  1. -1. -1.]
 [ 1. -1.  1.  1.  1.  1. -1.  1. -1.  1.]
 [-1.  1.  1. -1. -1.  1.  1.  1. -1.  1.]
 [ 1.  1. -1.  1. -1.  1. -1. -1.  1.  1.]
 [ 1.  1. -1. -1. -1.  1. -1.  1. -1. -1.]
 [ 1. -1. -1.  1. -1.  1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.  1. -1.  1. -1.  1.]
 [ 1. -1. -1. -1.  1.  1.  1. -1. -1.  1.]
 [-1. -1.  1.  1.  1. -1.  1.  1.  1. -1.]
 [ 1. -1.  1. -1.  1.  1.  1.  1.  1. -1.]]


In [6]:
ising_simulation(init_lattice)

[[0. 0. 0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Delta E:  -16.0
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Delta E:  0.0
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 

In [7]:
# #Flip a spin
# new_state = choose_flip(init_lattice, n_spins)
# new_lattice = new_state[0]
# print(new_state[1])
# print(new_state[2])

# #calculate energy difference
# en_diff = energy_difference(init_lattice, new_lattice)
# print(en_diff)